replicaCount: 1
image:
  repository: kevinhood/python-app
  pullPolicy: IfNotPresent
  tag: 0fe8ae
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 5000
ingress:
  enabled: true
  className: 'nginx'
  annotations: {}
  hosts:
    - host: python-app.test.com
      paths:
        - path: /
          pathType: Prefix
  tls: []
httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - chart-example.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /headers
resources: {}
livenessProbe:
  httpGet:
    path: /app/v1/healthz
    port: http
readinessProbe:
  httpGet:
    path: /app/v1/healthz
    port: http
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
